### ISSUE TITLE
How to add more permissions?

### ISSUE THREAD

**Issue by pztrn** [xyproto/permissionsql#3]
In README:

> Only supports "public", "user" and "admin" permissions out of the box, but offers functionality for implementing more fine grained permissions, if so desired.

Okay, but in docs (and source) there is no possibility to implement other permissions besides these three without patching the source. Is this marketing shit or I missed something?

**Comment by xyproto** [comment]
It's possible, will add an example to the README.

**Comment by xyproto** [comment]
It should be similar to this: https://github.com/xyproto/permissions2/blob/master/README.md#setting-and-getting-properties-for-users

**Comment by pztrn** [comment]
Yeah, placing an example in README will be great, thanks!

**Comment by pztrn** [comment]
Thanks!
