### ISSUE TITLE
permissionsql => permissionsqlite

### ISSUE THREAD

**Issue by terminar** [xyproto/permissionsql#4]
Hey Alexander,

I wanted to inform you that I have forked this project and "translated" it into permissionsqlite using, well.... simplesqlite (see comment at https://github.com/xyproto/simplemaria/issues/3).

You can find it at https://github.com/terminar/permissionsqlite

Hope that was OK, I am still testing if everything works but the tests are finishing/OK.

Maybe it is possible and makes sense to extend permissionsql to support both (simplemaria and simplesqlite?) via some sort of switch/connectionstring/whatever? Just an idea.

Again, thank you for your work, greetings!
Björn

**Comment by xyproto** [comment]
Hi Björn! Thanks for the forks and notifications. :+1:

An overall package or solution that makes it possible to quickly toggle between backends/connection strings is a good idea!

**Comment by xyproto** [comment]
FYI, Algernon is in the process of getting SQLite support thanks to the permissionsqlite package. :)

https://github.com/xyproto/algernon/issues/134
